#!/bin/sh
set -e

CRAWLER_DB="${CRAWLER_DB_NAME:-item}"
PAYMENT_DB="${PAYMENT_DB_NAME:-payment}"
APP_USER="${MYSQL_USER:-mysql}"

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${CRAWLER_DB}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON \`${CRAWLER_DB}\`.* TO '${APP_USER}'@'%';
CREATE DATABASE IF NOT EXISTS \`${PAYMENT_DB}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON \`${PAYMENT_DB}\`.* TO '${APP_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
